version: '3.8'

services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8188:8188"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s